### ISSUE TITLE
As a user I want to find a route between 2 points using digiroad map data

### ISSUE THREAD

**Issue by sepaww** [HY-OHTUPROJ-OSRM/OSRM-Test-Program#1]
# Subtasks

- [x] Download Digiroad2
- [x] Upload data to sql
- [x] Combine digiroad layers
- [x] Convert map data to osm
- [x] Convert osm to osrm
- [x] Start osrm-backend
- [ ] Automate map data transformation

# Acceptance criteria

- [ ] The story satisfies [DoD](https://github.com/HY-OHTUPROJ-OSRM/OSRM-Test-Program/blob/master/doc/Definition%20of%20done)

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] The solution has been implemented and deployed
